ClothBazar.Web/ViewModels/ProductViewModel.cs
using ClothBazar.Entites;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClothBazar.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public int PageNo { get; set; }
        public string SearchTerm { get; set; }
        public List<Product> Products { get; set; }
        public Product Product { get; set; }
        public Pager Pager { get; set; }
    }
    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvailableCategories { get; set; }
    }

    public class EditProductViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }
        public List<Category> AvailableCategories { get; set; }
    }

    

}

ClothBazar.Web/Controllers/ProductController.cs
using ClothBazar.Entites;
using ClothBazar.Web.ViewModels;
using ClothBazarServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string Search,int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.PageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1: 1;
            model.Products = ProductService.Instance.GetProducts(model.PageNo);
            model.Pager = new Pager(ProductService.Instance.GetProducts(), pageNo);
            if (string.IsNullOrEmpty(Search) == false)
            {
                model.SearchTerm = Search;
                model.Products = model.Products.Where(x => x.Name.ToLower().Contains(Search.ToLower())).ToList();
            }
            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoryService.Instance.GetAllCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newProduct = new Product();
                newProduct.Name = model.Name;
                newProduct.Description = model.Description;
                newProduct.Price = model.Price;
                newProduct.Category = CategoryService.Instance.GetCategory(model.CategoryID);
                newProduct.ImageURL = model.ImageURL;
                ProductService.Instance.SaveProduct(newProduct);
                return RedirectToAction("ProductTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();
            var product = ProductService.Instance.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageURL = product.ImageURL;
            model.AvailableCategories = CategoryService.Instance.GetAllCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var product = ProductService.Instance.GetProduct(model.ID);
            product.Name = model.Name;
            product.Description = model.Description;
            product.Price = model.Price;
            product.Category = null;
            product.CategoryID = model.CategoryID;
            if(product.ImageURL == null)
            {
                product.ImageURL = ProductService.Instance.GetProduct(model.ID).ImageURL;
            }
            ProductService.Instance.UpdateProduct(product);
            return RedirectToAction("ProductTable");
        }
     
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductService.Instance.DeleteProduct(ID);
            return RedirectToAction("ProductTable");
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.Product = ProductService.Instance.GetProduct(id);
            return View(model);
        }
    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Activities;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                file.SaveAs(path);
                 result.Data = new { Success = true, ImageURL = string.Format("/Content/images/{0}",fileName) };

                //    var newImage = new Image() { Name = fileName };
                //    if(ImageService.Instance.SaveNewImage(newImage))
                //    {
                //        result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath,fileName) };
                //    }
                //    else
                //    {
                //        result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //    }
                }
                catch(Exception ex)
                {
                    result.Data = new  { Success = false, Message = ex.Message};
                }
                return result;
        }
    }
}

ClothBazar.Web/Views/Product/Create.cshtml
@model NewProductViewModel
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/blank-image.png";

}
<h2>Create Product</h2>
<form method="post" id="CreateProduct">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select type="text" class="form-control" name="categoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        <option type="text" value="@category.ID">@category.Name</option>
                    }
                </select>
                </div>
            <div class="form-group">
                <lable>Name</lable>
                <input class="form-control" type="text" name="Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" type="text" name="Description" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input class="form-control" type="text" name="Price" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
            </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
        </div>
    
</form>
<script type="text/javascript">
    $("#saveBtn").click(function () {
        debugger
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Create", "Product")',
            data: $("#CreateProduct").serialize()
        })
        .done(function (response) {
            $("#tableContainer").html(response);
            $("#actionContainer").html('');
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            swal({
                title: "Warning",
                text: "Please enter all required fields.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        });
    });
    $("#imageUpload").change(function () {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: 'POST',
            url: '@Url.Action("UploadImage", "Shared")',
            dataType: 'json',
            data: formData,
            contentType: false,
            processData: false
        })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#ImageURL").val(response.ImageURL);
                $("#productImage").attr("src", response.ImageURL);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContiner");
    });
    $('#CreateProduct').validate({
        rules: {
            Name: {
                required: true,
                minlength: 4,
                maxlenght: 50,
            },
            Description: {
                maxlenght: 500
            },
            Price: {
                range:[1,100000]
            }

        },
        messages: {
        Name: {
                required: 'Name is required',
                minlength: 'Minimum Length is 4',
                maxlength: 'Maximum Length is 50'
        },
        Description: {
                maxlength: 'Maximum Length is 500'
        },
        Price: {
                range: 'Price must be within range of 1 - 100000.'
        }
    }
        
    });
    </script>

ClothBazar.Web/Views/Product/Edit.cshtml
@model EditProductViewModel

@{
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/blank-image.png";
}
<h2>Edit Product</h2>

<form id="editProduct">
    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-control" name="CategoryID">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.ID == Model.CategoryID ? "selected" : string.Empty;
                        <option value="@category.ID" @selected>@category.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Price</label>
                <input class="form-control" name="Price" value="@Model.Price" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>

            <button id="updateBtn" type="button" class="btn btn-primary">Update</button>
            <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="productImage" src="@imageURL" />
            </div>
        </div>
    </div>

</form>

<script>
	$('#editProduct').validate({
		rules: {
			Name: {
				required: true,
				minlength: 4,
				maxlength: 50,
			},
			Description: {
				maxlength: 500
			},
			Price: {
				range: [1, 100000]
			}
		},
		messages: {
			Name: {
				required: 'Name is required',
				minlength: 'Minimum Length is 4',
				maxlength: 'Maximum Length is 50'
			},
			Description: {
				maxlength: 'Maximum Length is 500'
			},
			Price: {
				range: 'Price must be within range of 1 - 100000.'
			}
		}
	});
	$("#imageUpload").change(function () {
		var element = this;
		var formData = new FormData();
		var totalFiles = element.files.length;
		for (var i = 0; i < totalFiles; i++) {
			var file = element.files[i];
			formData.append("Photo", file);
		}
		$.ajax({
			type: 'POST',
			url: '@Url.Action("UploadImage", "Shared")',
			dataType: 'json',
			data: formData,
			contentType: false,
			processData: false
		})
        .done(function (response) {
        	console.log(response);
        	if (response.Success) {
        		$("#ImageURL").val(response.ImageURL);
        		$("#productImage").attr("src", response.ImageURL);
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});
	$("#updateBtn").click(function () {
		if ($("#editProduct").valid()) {
			$.ajax({
				type: 'POST',
				url: '@Url.Action("Edit", "Product")',
				data: $("#editProduct").serialize()
			})
			.done(function (response) {
			    $("#tableContiner").html(response);
			    $("#actionContainer").html("");
			    location.reload();
			    focusAction("tableContiner");
			})
			.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				alert("FAIL");
			});
		}
		else {
			swal({
				title: "Warning",
				text: "Please enter all valid data in fields.",
				icon: "warning",
				buttons: true,
				dangerMode: true,
			});
		}
	});
	$("#cancelBtn").click(function () {
		$("#actionContainer").html("");
		focusAction("tableContiner");
	});
</script>

ClothBazar.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="container">
<div id="tableContainer">
    @{
    Html.RenderAction("ProductTable");
 //   Html.RenderAction("Create");  
 
}
</div>
    <div id="actionContainer">
    </div>
</div>
<script>
	function focusAction(controlToFocus) {
		$('html, body').animate({
			scrollTop: $("#" + controlToFocus).offset().top - 100
		}, 1000);
	}
</script>

ClothBazar.Web/Views/Product/ProductTable.cshtml
@model ProductSearchViewModel
<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Products
                    </h2>
                </div>
            </div>
        </div>
        <div>
            <div>
                <form method="post">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Search</label>
                                <input type="Search" class="form-control" id="searchTxt" aria-describedby="searchTxt" value="@Model.SearchTerm" placeholder="Enter Product Name To Search" />
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label>Action</label>
                                <div class="row"></div>
                                <button id="searchBtn" type="button">Search</button>
                                <button id="resetBtn" type="button">Reset</button>
                                <button id="newBtn" type="button">New</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>

            <div>
                <p class="showing-product float-right">
                    Showing @((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize + 1) – @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + (Model.Products.Count < Model.Pager.PageSize ? Model.Products.Count : Model.Pager.PageSize)) of @Model.Pager.TotalItems Products
                </p>
                <table id="table_id" class="table table-striped">
                    <thead>
                        <tr>
                            <th class="font-weight-bold">Product Name</th>
                            <th class="font-weight-bold">Category</th>
                            <th class="font-weight-bold">Price</th>
                            <th class="font-weight-bold wrap-td">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                                <tr>
                                    <td>@product.Name</td>
                                    <td>
                                        @if (product.Category != null)
                    {
                                        <text>@product.Category.Name</text>
                                    }
                                    else
                                    {
                                        <text>-</text>
                                    }
                                </td>
                                <td>@product.Price</td>
                                <td class="wrap-td">
                                    <button class="editBtn" data-id="@product.ID">Edit</button>
                                    <button class="deleteBtn" data-id="@product.ID">Delete</button>
                                    <button class="addtoCart" data-id="@product.ID">Add To Cart</button>
                                </td>
                            </tr>
                            }
                        }
                        else
                        {
                            <tr>
                                <td class="text-danger" colspan="4">No Products found.</td>
                            </tr>
                        }
                    </tbody>
                </table>
                @if (Model.Pager != null && Model.Pager.TotalPages > 1)
                {
                    <div class="product-pagination text-center clearfix">
                        <ul class="flat-pagination">
                            @if (Model.Pager.CurrentPage > 1)
                            {
                                <li class="prev">
                                    <a href="@Url.Action("Index", "Product", new { pageNo = Model.Pager.CurrentPage - 1})"><i class="fa fa-angle-left"></i></a>
                                </li>}

                            @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                            {
                                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                                <li class="@activeClass"><a href="@Url.Action("Index", "Product", new { pageNo = page })">@page</a></li>}

                            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                            {
                                <li><a href="@Url.Action("Index", "Product", new { pageNo = Model.Pager.CurrentPage + 1})"><i class="fa fa-angle-right"></i></a></li>}
                        </ul><!-- /.flat-pagination -->
                    </div>
                }
                <div>
                    @*@if (Model.PageNo != 1)
                    {
                        <button class="pageButtons" data-pageNo="@(Model.PageNo-1)">Previous</button>
                    }
                    @if (Model.Products != null && Model.Products.Count > 0)
                    {
                        <button class="pageButtons" data-pageNo="@(Model.PageNo + 1)">Next</button>
                    }*@
                </div>
            </div>
            <hr />
        </div>


</section>
<script type="text/javascript">

    $(".pageButtons").click(function ()
    {
        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',
            data: {
                pageNo: $(this).attr("data-pageNo")
            }

               })
            .done(function (response) {
            $("#tableContainer").html(response);
        })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        })
    });
    $("#resetBtn").click(function () {
        $("#searchTxt").val("");
        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',

        })
        .done(function (response) {
            $("#tableContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");

        })
    });
    $("#searchBtn").click(function () {
        var searchvalue = $("#searchTxt").val();
        $.ajax({
            url: '@Url.Action("ProductTable", "Product")',
            data: {
                search: searchvalue
            }
        })
        .done(function (response) {
            $("#tableContainer").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");

        })
    });
    $("#newBtn").click(function () {
        debugger
        $.ajax({
            url: '@Url.Action("Create", "Product")'

        })
        .done(function (response)
        {
            debugger
            $("#actionContainer").html(response);
            focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        })
    });
    $(".editBtn").click(function () {
        debugger
        $.ajax({
            url: '@Url.Action("Edit", "Product")',
            data: {
                ID: $(this).attr("data-id")
            }
        })
        .done(function (response) {
            $("#actionContainer").html(response);
            focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("edit response failed");

        });
    });
    var products = [];
    $(".addtoCart").click(function () {
        var productID = $(this).attr('data-id');
        products.push(productID);
        $.cookie('CartProducts', products.join('-'), { path: '/' });

    });

    $(".deleteBtn").click(function () {

        swal({
            title: "Confirm?",
            text: "Are you sure you want to delete this product?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
		.then((willDelete) => {
		    if (willDelete) {
		        $.ajax({
		            type: 'POST',
		            url: '@Url.Action("Delete", "Product")',
		            data: {
		                ID: $(this).attr('data-id')
		            }
		        })
				.done(function (response) {

				    $("#tableContiner").html(response);

				    swal("Record deleted Successfully.",
                        {
                            icon: "success",
                        });
				    
				})
				.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				    alert("FAIL");
				});

		    }
		})
    });

</script>