ClothBazar.Web/ViewModels/ShopViewModels.cs
using ClothBazar.Entites;
using ClothBazar.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ClothBazar.Web.ViewModels
{
    public class CheckoutViewModel
    {
        public List<Product> CartProducts { get; set; }
        public List<int> CartProductIDs { get; set; }
        public ApplicationUser User { get; set; }

    }
    public class ShopViewModel
    {
        public int MaximumPrice { get; set; }
        public List<Category> FeaturedCategories { get; set; }
        public List<Product> Products { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get;  set; }
        public Pager Pager { get; set; }
        public int PageNo { get; set; }
        public string SearchTerm { get; set; }
    }
    public class FilterProductViewModel
    {
        public List<Product> Products { get; set; }

        public Pager Pager { get; set; }
        public int? SortBy { get; set; }
        public int? CategoryID { get; set; }
        public string SearchTerm { get; set; }
        public int PageNo { get; set; }

    }
}

ClothBazar.Web/Controllers/ProductController.cs
using ClothBazar.Entites;
using ClothBazar.Web.ViewModels;
using ClothBazarServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class ProductController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductTable(string Search,int? pageNo)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.PageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1: 1;
            model.Products = ProductService.Instance.GetProducts(model.PageNo);
            model.Pager = new Pager(ProductService.Instance.GetProducts(), pageNo);
            if (string.IsNullOrEmpty(Search) == false)
            {
                model.SearchTerm = Search;
                model.Products = model.Products.Where(x => x.Name.ToLower().Contains(Search.ToLower())).ToList();
            }
            return PartialView(model);
        }
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories = CategoryService.Instance.GetAllCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Create(NewProductViewModel model)
        {
            if (ModelState.IsValid)
            {
                var newProduct = new Product();
                newProduct.Name = model.Name;
                newProduct.Description = model.Description;
                newProduct.Price = model.Price;
                newProduct.Category = CategoryService.Instance.GetCategory(model.CategoryID);
                newProduct.ImageURL = model.ImageURL;
                ProductService.Instance.SaveProduct(newProduct);
                return RedirectToAction("ProductTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductViewModel model = new EditProductViewModel();
            var product = ProductService.Instance.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageURL = product.ImageURL;
            model.AvailableCategories = CategoryService.Instance.GetAllCategories();
            return PartialView(model);
        }
        [HttpPost]
        public ActionResult Edit(EditProductViewModel model)
        {
            var product = ProductService.Instance.GetProduct(model.ID);
            product.Name = model.Name;
            product.Description = model.Description;
            product.Price = model.Price;
            product.Category = null;
            product.CategoryID = model.CategoryID;
            if(product.ImageURL == null)
            {
                product.ImageURL = ProductService.Instance.GetProduct(model.ID).ImageURL;
            }
            ProductService.Instance.UpdateProduct(product);
            return RedirectToAction("ProductTable");
        }
     
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            ProductService.Instance.DeleteProduct(ID);
            return RedirectToAction("ProductTable");
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            ProductSearchViewModel model = new ProductSearchViewModel();
            model.Product = ProductService.Instance.GetProduct(id);
            return View(model);
        }
    }
}

ClothBazar.Web/Controllers/ShopController.cs
using ClothBazar.Web.Code;
using ClothBazar.Web.ViewModels;
using ClothBazarServices;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class ShopController : Controller
    {
        private ApplicationSignInManager _signInManager;
        private ApplicationUserManager _userManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ActionResult Index(string searchTerm,int? minimumPrice,int? maximumPrice,int? categoryID,int? sortBy, int? pageNo)
        {
            ShopViewModel model = new ShopViewModel();
            model.SearchTerm = searchTerm;
            model.FeaturedCategories = CategoryService.Instance.GetFeaturedCategories();
            model.MaximumPrice = ProductService.Instance.GetMaximumPrice();
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.Products = ProductService.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID,sortBy, pageNo.Value,10);
            model.SortBy = sortBy;
            model.CategoryID = categoryID;
            int totalCount = ProductService.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Pager = new Pager(totalCount,pageNo);
            model.PageNo = pageNo.Value;
            return View(model);
        }
        public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximumPrice, int? categoryID, int? sortBy, int? pageNo)
        {
            var pageSize = int.Parse(@ConfigurationService.Instance.GetConfig("ListingPageSize").Value);
            FilterProductViewModel model = new FilterProductViewModel();
            model.SearchTerm = searchTerm;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.SortBy = sortBy;
            model.CategoryID = categoryID;
            model.Products = ProductService.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy, pageNo.Value, 10);
            int totalCount = ProductService.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, categoryID, sortBy);
            model.Pager = new Pager(totalCount, pageNo,pageSize);
            
            return PartialView(model);
        }
        [Authorize]
        public ActionResult Checkout()
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var CartProductsCookie = Request.Cookies["CartProducts"];

            if (CartProductsCookie != null && !string.IsNullOrEmpty(CartProductsCookie.Value))
            {
                model.CartProductIDs = CartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductService.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());
            }
            return View(model);
        }
    }
}

ClothBazar.Web/Views/Shop/Checkout.cshtml
@model CheckoutViewModel

@if (Model != null && Model.CartProducts != null && Model.CartProducts.Count > 0)
{
    var i = 1;
    <section class="flat-row main-shop shop-slidebar">
        <div class="container">
            <div class="row">
                <div class="col-md-4 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted">Your cart</span>
                    </h4>
                    <ul class="list-group mb-3">
                        @foreach (var product in Model.CartProducts)
                        {
                            var productQuantity = Model.CartProductIDs.Where(productID => productID == product.ID).Count();

                            <li class="list-group-item d-flex justify-content-between lh-condensed" data-id="@product.ID">
                                <div>
                                    <h6 class="my-0">@i - @product.Name - Qty: @productQuantity</h6>
                                    <small class="text-muted">@(product.Description.Length > 100 ? product.Description.Substring(0, 99) : product.Description)</small>
                                </div>
                                <span class="text-muted">Unit Price: $ @product.Price - Total Price: @(productQuantity * product.Price)</span>
                            </li>i++;
                        }

                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (USD)</span>
                            <strong>$ @Model.CartProducts.Sum(x => x.Price * Model.CartProductIDs.Where(productID => productID == x.ID).Count())</strong>
                        </li>
                    </ul>
                </div>
                <div class="col-md-8 order-md-1">
                    <h4 class="mb-3">Billing address</h4>
                    <form class="needs-validation" novalidate="">
                        <div class="row">
                            <div class="col-md-12 mb-3">
                                <label for="firstName">Name</label>
                                <input type="text" class="form-control" id="Name" placeholder="" value="@Model.User.Name" required="">
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="email">Email <span class="text-muted">(Optional)</span></label>
                            <input type="email" class="form-control" id="Email" placeholder="you@example.com" value="@Model.User.Email">
                        </div>

                        <div class="mb-3">
                            <label for="address">Address</label>
                            <input type="text" class="form-control" id="address" placeholder="1234 Main St" required="" value="@Model.User.Address">
                        </div>

                        <hr class="mb-4">
                        <button id="placeOrderBtn" class="btn btn-primary btn-lg btn-block" type="button">Place Order!</button>
                    </form>
                </div>
            </div>
        </div><!-- /.container -->
    </section>


    <script>
	$("#placeOrderBtn").click(function () {
		$.ajax({
			url: '@Url.Action("PlaceOrder", "Shop")',
			data: {
				productIDs: '@string.Join("-", Model.CartProductIDs)'
			}
		})
        .done(function (response) {
        	if(response.Success)
        	{
        		$.cookie('CartProducts', '', { path: '/' });
        		updateCartProducts();
        		swal("Done", "Your Order has been placed.", "success").then((value) => {
        			window.location = '@Url.Action("Index", "Shop")';
        		});;
        	}
        	else{
        		swal("Failed", "Unable to place order.", "warning");
        	}
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});
    </script>
}
else
{
    <div>
        <b>No Products in Cart.</b>
    </div>
}

ClothBazar.Web/Views/Shop/FilterProducts.cshtml
@model FilterProductViewModel
<div class="filter-shop clearfix">
    <p class="showing-product float-right">
        Showing @((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize + 1) – @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + (Model.Products.Count < Model.Pager.PageSize ? Model.Products.Count : Model.Pager.PageSize)) of @Model.Pager.TotalItems Products
    </p>
</div><!-- /.filte-shop -->
<div class="product-content product-threecolumn product-slidebar clearfix">
    <ul class="product style2 sd1">
        @foreach (var product in Model.Products)
        {
            <li class="product-item">
                <div class="product-thumb clearfix">
                    <a href='@Url.Action("Details","Product", new { ID = product.ID})'>
                        <img class="thumb" src="@ProductService.Instance.ImageURL(product)"  alt="image">
                    </a>
                </div>
                <div class="product-info clearfix">
                    <span class="product-title">@product.Name</span>
                    <div class="price">
                        <ins>
                            <span class="amount">$@product.Price</span>
                        </ins>
                    </div>
                </div>
                <div class="add-to-cart text-center">
                    <a class="productAddToCart" data-id="@product.ID">ADD TO CART</a>
                </div>
                <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
            </li>

        }
    </ul><!-- /.product -->
</div><!-- /.product-content -->

@if (Model.Pager != null && Model.Pager.TotalPages > 1)
{
    <div class="product-pagination text-center clearfix">
        <ul class="flat-pagination">
            @if (Model.Pager.CurrentPage > 1)
            {
                <li class="prev">
                    <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage - 1, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class="pageDataLink"><i class="fa fa-angle-left"></i></a>
                </li>}

            @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <li class="@activeClass"><a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = page, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class="pageDataLink">@page</a></li>}

            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <li><a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage + 1, sortBy = Model.SortBy, categoryID = Model.CategoryID })" class="pageDataLink"><i class="fa fa-angle-right"></i></a></li>}
        </ul><!-- /.flat-pagination -->
    </div>
}

<input type="hidden" id="SearchTerm" value="@Model.SearchTerm" />
<input type="hidden" id="SortBy" value="@Model.SortBy" />
<input type="hidden" id="CategoryID" value="@Model.CategoryID" />
<script>
    $(".pageDataLink").click(function () {
        var url = $(this).attr("data-href");
        if (url != "" || url != undefined) {
            GetData(url);
        }
    });
    var products;
    $(".productAddToCart").click(function () {
        debugger
        var existingCookieData = $.cookie('CartProducts');
        if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null)
        {
            products = existingCookieData.split("-");
        }
        else {
            products = [];
        }
            var productID = $(this).attr('data-id');
            products.push(productID);
            $.cookie('CartProducts', products.join('-'), { path: '/' });
            updateCartCount();
            swal( "Done","Product Added To Cart.","success");
    });
</script>

ClothBazar.Web/Views/Shop/Index.cshtml
@using ClothBazar.Web.Code
@model ShopViewModel
@{
    ViewBag.Title = "Index";
}
    	<!-- Page title -->
<div class="page-title parallax parallax1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-heading">
                    <h1 class="title">Shop</h1>
                </div><!-- /.page-title-heading -->

            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.page-title -->

<section class="flat-row main-shop shop-slidebar">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar slidebar-shop">
                    <div class="widget widget-search">
                        <form role="search" method="get" class="search-form" action="@Url.Action("Index", "Shop")">
                            <label>
                                <input type="search" id="searchText" class="search-field" placeholder="Search …" value="@Model.SearchTerm" name="searchTerm">
                            </label>
                            <input type="button" id="searchBtn" class="search-submit" value="Search">
                        </form>
                    </div><!-- /.widget-search -->
                    <div class="widget widget-sort-by">
                        <h5 class="widget-title">
                            Sort By
                        </h5>
                        <ul>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnum.Default , categoryID = Model.CategoryID})" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnum.Default ? "active" : string.Empty : string.Empty)">Default</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnum.Popularity , categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnum.Popularity ? "active" : string.Empty : string.Empty)">Popularity</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnum.PriceLowToHigh , categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnum.PriceLowToHigh ? "active" : string.Empty : string.Empty)">Price: low to high</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEnum.PriceHighToLow , categoryID = Model.CategoryID })" class="dataLink @(Model.SortBy.HasValue ? Model.SortBy.Value == (int)SortByEnum.PriceHighToLow ? "active" : string.Empty : string.Empty)">Price: high to low</a></li>
                        </ul>
                    </div>
                    
                    <div class="widget widget_tag">
                        <h5 class="widget-title">
                            Featured Categories
                        </h5>
                        <div class="tag-list">
                            @foreach (var category in Model.FeaturedCategories)
                            {
                                <a data-href="@Url.Action("FilterProducts", "Shop", new { categoryID = category.ID , sortBy = Model.SortBy })" class="dataLink  @(Model.CategoryID.HasValue && Model.CategoryID.Value == category.ID ? "active" : string.Empty  )">@category.Name</a>
                            }
                        </div>
                    </div><!-- /.widget -->
                    <div class="widget widget-price">
                        <h5 class="widget-title">Filter by price</h5>
                        <div class="price-filter">
                            <div id="slide-range"></div>
                            <p class="amount">
                                Price: <input type="text" id="amount" disabled="">
                            </p>
                        </div>
                    </div>
                <a href="@Url.Action("Index","Shop")" class="btn bg-danger">Reset Filters</a>
                </div><!-- /.sidebar -->
            </div><!-- /.col-md-3 -->
            <div class="col-md-9">
                <div id="productsDiv">
                    @{
                        var filterProductViewModel = new FilterProductViewModel();
                        filterProductViewModel.Products = Model.Products;
                        filterProductViewModel.Pager = Model.Pager;
                        Html.RenderPartial("FilterProducts", filterProductViewModel);
                    }
                </div>

            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.flat-row -->
<script>
    var callTimeout;
    var priceSlider = $("#slide-range").slider({
        range: true,
        min: 0,
        max: @Model.MaximumPrice,
        values: [0, @Model.MaximumPrice],
        slide: function (event, ui) {
            var minPrice = ui.values[0];
            var maxPrice = ui.values[1];
            $("#amount").val("$" + ui.values[0] + ".00" + " - " + "$" + ui.values[1] + ".00");
            clearTimeout(callTimeout);
            callTimeout = setTimeout(PriceRangeChange,500)
        }
    });
    $(".dataLink").click(function(){
        var url = $(this).attr("data-href");
        if(url != "" || url != undefined){
            GetData(url);
        }
    });

    function GetData(dUrl){
        $.ajax({
            url: dUrl,
            data: {
                minimumPrice : priceSlider.slider("values",0),
                maximumPrice : priceSlider.slider("values",1)
            }
        })
        .done(function (response) {
            $("#productsDiv").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    }

    function PriceRangeChange(){

        $.ajax({
            url: '@Url.Action("FilterProducts","Shop")',
            data: {
				sortBy: $("#SortBy").val(),
				categoryID: $("#CategoryID").val(),
				minimumPrice : priceSlider.slider("values", 0),
				maximumPrice : priceSlider.slider("values", 1)
            }
        })
        .done(function (response) {
            $("#productsDiv").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        })
    }
    $("#searchBtn").click(function () {
        debugger
        $.ajax({
            url: '@Url.Action("FilterProducts", "Shop")',
            data: {
                searchTerm : $("#searchText").val()
            }
        })
        .done(function (response) {
            $("#productsDiv").html(response);
            $("#searchBtn").val(searchvalue);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");

        })
    });
</script>