ClothBazar.Web/ViewModels/CAtegoryViewModels.cs
using ClothBazar.Entites;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClothBazar.Web.ViewModels
{
    public class NewCategoryViewModel
    {
        public int id { get; set; }
        [Required]
        [MinLength(5),MaxLength(50)]
        public string Name { get; set; }
        [MaxLength(500)]
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string imageURL { get; set; }
        public List<Category> Categories { get; set; }
    }
}

ClothBazar.Web/Controllers/CategoryController.cs
using ClothBazar.Entites;
using ClothBazar.Web.ViewModels;
using ClothBazarServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ClothBazar.Web.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        public ActionResult Index()
        {
            var categories = CategoryService.Instance.GetAllCategories();
            return View(categories); 
        }
        public ActionResult CategoryTable(string search, int? pageNo)
        {
            CategorySearchViewModel model = new CategorySearchViewModel();
            model.SearchTerm = search;

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            var totalRecords = CategoryService.Instance.GetCategoriesCount(search);
            model.Categories = CategoryService.Instance.GetCategories(search, pageNo.Value);

            if (model.Categories != null)
            {
                model.Pager = new Pager(totalRecords, pageNo,3);

                return PartialView("CategoryTable", model);
            }
            else
            {
                return HttpNotFound();
            }
        }
    
        [HttpGet]
        public ActionResult Create()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult Create(Category category)
        {
            if (ModelState.IsValid)
            {
                CategoryService.Instance.SaveCategory(category);
                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
        }
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            var category = CategoryService.Instance.GetCategory(ID);
            return PartialView(category);
        }
        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (category.ImageURL == null)
            {
                category.ImageURL = CategoryService.Instance.GetCategory(category.ID).ImageURL;
            }
            CategoryService.Instance.UpdateCategory(category);
            return RedirectToAction("CategoryTable");
        }
        [HttpPost]
        public ActionResult Delete(Category category)
        {
            CategoryService.Instance.DeleteCategory(category.ID);
            return RedirectToAction("CategoryTable");
        }
    }
}

ClothBazar.Web/Controllers/SharedController.cs
using System;
using System.Activities;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClothBazar.Web.Controllers
{
    public class SharedController : Controller
    {
        // GET: Shared
        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
            try
            {
                var file = Request.Files[0];
                var fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                var path = Path.Combine(Server.MapPath("~/Content/images/"), fileName);
                file.SaveAs(path);
                 result.Data = new { Success = true, ImageURL = string.Format("/Content/images/{0}",fileName) };

                //    var newImage = new Image() { Name = fileName };
                //    if(ImageService.Instance.SaveNewImage(newImage))
                //    {
                //        result.Data = new { Success = true, Image = fileName, File = newImage.ID, ImageURL = string.Format("{0}{1}", Variables.ImageFolderPath,fileName) };
                //    }
                //    else
                //    {
                //        result.Data = new { success = false, Message = new HttpStatusCodeResult(500) };
                //    }
                }
                catch(Exception ex)
                {
                    result.Data = new  { Success = false, Message = ex.Message};
                }
                return result;
        }
    }
}

ClothBazar.Web/Views/Category/CategoryTable.cshtml
@model ClothBazar.Web.ViewModels.CategorySearchViewModel
@{
    ViewBag.Title = "CategoryTable";
}
<div>
    <form method="post">
        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    <label>Search</label>
                    <input type="Search" class="form-control" id="searchTxt" aria-describedby="searchTxt" placeholder="Enter Category Name To Search" />
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group">
                    <label>Action</label>
                    <div class="row"></div>
                    <button id="searchBtn" type="button">Search</button>
                    <button id="newBtn" type="button">New</button>
                </div>
            </div>
        </div>
    </form>
</div>
<div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="font-weight-bold">Category Name</th>
                <th class="font-weight-bold">Product Count</th>
                <th class="font-weight-bold wrap-th">Actions</th>
            </tr>
        </thead>
        <tbody>
         @if (Model.Categories != null && Model.Categories.Count > 0)
         {
            foreach (var category in Model.Categories)
            {


                <tr>
                    <td>@category.Name</td>
                    <td>
                        @category.Products.Count
                    <td>
                        <button class="editBtn" data-id="@category.ID">Edit</button>
                        <button class="deleteBtn" data-id="@category.ID">Delete</button>
                    </td>
                </tr>

            }
         }

        </tbody>
    </table>
    <div>
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {

            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageno="1">First</button>
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage - 1)">Previous</button>}

            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class="@activeClass pageButtons" data-pageno="@page">@page</button>}

            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageno="@(Model.Pager.CurrentPage + 1)">Next</button>
                <button class="pageButtons" data-pageno="@Model.Pager.EndPage">Last</button>}
        }
    </div>
</div>

<hr>
<script type="text/javascript">
    $("#searchBtn").click(function () {
        var searchvalue = $("#searchTxt").val();
        $.ajax({
            url: '@Url.Action("CategoryTable", "Category")',
            data: {
                Search: searchvalue
                   }
                })
        .done(function (response) {
            $("#tableContiner").html(response);
            $("#searchTxt").val(searchvalue);
            })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");

              })
    });
    $("#newBtn").click(function () {
        debugger
        $.ajax({
            url: '@Url.Action("Create", "Category")',

        })
        .done(function (response)
        {
            debugger
            $("#actionContainer").html(response);
            focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        })
    });
    $(".editBtn").click(function () {
        $.ajax({
            url: '@Url.Action("Edit", "Category")',
            data: {
                ID: $(this).attr("data-id")
            }

        })
        .done(function (response) {
            $("#actionContainer").html(response);
            focusAction("actionContainer");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");

        })
    });
   $(".deleteBtn").click(function () {

        swal({
            title: "Confirm?",
            text: "Are you sure you want to delete this product?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
		.then((willDelete) => {
		    if (willDelete) {
		        $.ajax({
		            type: 'POST',
		            url: '@Url.Action("Delete", "Category")',
		            data: {
		                ID: $(this).attr('data-id')
		            }
		        })
				.done(function (response) {
				    $("#tableContiner").html(response);

				    swal("Record deleted Successfully.",
                        {
                            icon: "success",
                        });
				})
				.fail(function (XMLHttpRequest, textStatus, errorThrown) {
				    alert("FAIL");
				});

		    }
		})
   });
	$(".pageButtons").click(function () {
		$.ajax({
			url: '@Url.Action("CategoryTable", "Category")',
			data: {
				pageNo: $(this).attr("data-pageNo"),
				search: '@Model.SearchTerm'
			}
		})
        .done(function (response) {
        	$("#tableContiner").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
	});
</script>

ClothBazar.Web/Views/Category/Create.cshtml
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"></script>
@{
    ViewBag.Title = "Create";
    var imageURL = "/Content/images/blank-image.png";
}
<h2>Create Category</h2>


<form id="createCategory">
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Name <span class="text-danger">*</span></label>
                <input class="form-control" name="Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <label>Is Featured?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" /> False</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img class="img-thumbnail img-fluid" id="categoryImage" src="@imageURL" />
            </div>
        </div>
    </div>

    <button id="saveBtn" type="button" class="btn btn-primary">Save</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>
<script>
    $("#imageUpload").change(function ()
    {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0 ; i < totalFiles; i++)
        {
            var file = element.files[i];
            formData.append('Photo', file);
        }
        $.ajax
            ({
                type: 'POST',
                url: '@Url.Action("UploadImage","Shared")',
                dataType: 'json',
                data: formData,
                contentType: false,
                processData: false
            })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#categoryImage").attr("src", response.ImageURL);
                $("#ImageURL").val(response.ImageURL);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });
        
    });
 
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContiner");
    });
    $("#saveBtn").click(function () {
        debugger;
        
            $.ajax({
                type: 'POST',
                url: '@Url.Action("Create", "Category")',
                data: $("#createCategory").serialize()
            })
			.done(function (response) {
			    $("#tableContiner").html(response);
			    $("#actionContainer").html("");
			    focusAction("tableContiner");
			})
			.fail(function (XMLHttpRequest, textStatus, errorThrown) {
			    swal({
			        title: "Warning",
			        text: "Please enter all required fields.",
			        icon: "warning",
			        buttons: true,
			        dangerMode: true,
			    });
			});
      
    });
    $('#createCategory').validate({
        rules: {
            Name:{ 
                required: true,
                minlength: 5,
                maxlenght: 50,
            },
            Description:{
                maxlenght:500
            }
        },
        messages:{
        Name:{
                    required: 'Enter a name',
                    minlength: 'minimum lenght will be 5',
                    maxlenght: 'maxlenght will be 50'
        },
            Description:{
                maxlength: 'Maximum length will me 500'
            }
        }
    });
</script>

ClothBazar.Web/Views/Category/Delete.cshtml
@model ClothBazar.Entites.Category
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this Category ?</h3>
<form method="post">
    <label>@Model.ID</label><br/>
    <label>@Model.Name</label><br/>
    <label>@Model.Description</label>
    <button type="submit">Yes Delete</button>

</form>
<a href="~/Views/Category/Index.cshtml">Cancel</a>

ClothBazar.Web/Views/Category/Edit.cshtml
@model ClothBazar.Entites.Category
@{
    ViewBag.Title = "Edit";
    var trueFeature = Model.IsFeatured ? "checked" : string.Empty;
    var falseFeature = !Model.IsFeatured ? "checked" : string.Empty;
    var imageURL = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/images/blank-image.png";

}

<h2>Edit</h2>

<form id="editCategory">
    <input type="hidden" name="ID" value="@Model.ID" />

    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Name</label>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>
            <div class="form-group">
                <label>Description</label>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <label>Image</label>
                <input type="hidden" id="ImageURL" name="ImageURL" value="@Model.ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png, .jpg" />
            </div>
            <div class="form-group">
                <label>Is Featured?</label>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="True" @trueFeature /> True</label>
                    </div>
                    <div class="radio form-control">
                        <label><input name="isFeatured" type="radio" value="False" @falseFeature /> False</label>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img src="@imageURL" class="img-thumbnail img-fluid" id="categoryImage" />
            </div>
        </div>
    </div>

    <button id="updateBtn" type="button" class="btn btn-primary">Update</button>
    <button id="cancelBtn" type="button" class="btn btn-primary">Cancel</button>
</form>
<script>
    $("#imageUpload").change(function ()
    {
        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0 ; i < totalFiles; i++)
        {
            var file = element.files[i];
            formData.append('Photo', file);
        }
        $.ajax
            ({
                type: 'POST',
                url: '@Url.Action("UploadImage","Shared")',
                dataType: 'json',
                data: formData,
                contentType: false,
                processData: false
            })
        .done(function (response) {
            console.log(response);
            if (response.Success) {
                $("#categoryImage").attr("src", response.ImageURL);
                $("#ImageURL").val(response.ImageURL);
            }
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("Fail");
        });
    });
    $("#updateBtn").click(function () {
        $.ajax({
            type: 'POST',
            url: '@Url.Action("Edit", "Category")',
            data: $("#editCategory").serialize()
        })
        .done(function (response) {
            $("#tableContiner").html(response);
            $("#actionContainer").html("");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
            alert("FAIL");
        });
    });
    $("#cancelBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContiner");
    });
    $('#editCategory').validate({
        rules: {
            Name: {
                required: true,
                minlength:4,
                maxlength: 50,
            },
            Description: {
                maxlength: 500
            },
            Price: {
                range: [1, 100000]
            }
        },
        messages: {
            Name: {
                required: 'Name is required',
                minlength: 'Minimum Length is 4',
                maxlength: 'Maximum Length is 50'
            },
            Description: {
                maxlength: 'Maximum Length is 500'
            },
            Price: {
                range: 'Price must be within range of 1 - 100000.'
            }
        }
    });
</script>

ClothBazar.Web/Views/Category/Index.cshtml
@{
    ViewBag.Title = "Index";
}
   <section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Categories
                    </h2>
                </div>
            </div>
        </div>
        <div id="tableContiner">
            @{Html.RenderAction("CategoryTable");
            }
        </div>

        <hr />
        <div id="actionContainer">

        </div>
    </div>
</section>


<script>
	function focusAction(controlToFocus) {
		$('html, body').animate({
			scrollTop: $("#" + controlToFocus).offset().top - 100
		}, 1000);
	}
</script>